name: Dispatch Workflow
 
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'Doni'
      Enter_password:
        description: 'Enter your password'
        required: true
        default: '*****'
 
jobs:
  run_the_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Username and Favorite Color
        run: echo "${{ github.event.inputs.username }} is username, and password is ${{ github.event.inputs.Enter_password }}"
