name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'Doniyor'
      favorite_color:
        description: 'Favorite color'
        required: true
        default: 'white'
      item:
        description: 'Enter your item'
        required: true
        default: 'book'


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.output-username.outputs.username }}
      favorite_color: ${{ steps.output-favorite-color.outputs.favorite_color }}
      item: ${{ steps.output-item.outputs.item }}
    steps:
      - name: Echo Username
        id: output-username
        run: echo "username=${{ github.event.inputs.username }}" >> $GITHUB_OUTPUT
      - name: Echo Favorite Color
        id: output-favorite-color
        run: echo "favorite_color=${{ github.event.inputs.favorite_color }}" >> $GITHUB_OUTPUT 
      - name: Echo item
        id: output-item
        run: echo "item=${{ github.event.inputs.item }}" >> $GITHUB_OUTPUT


  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      GREETING: ${{ steps.greet.outputs.GREETING }}
    steps:
      - name: Create a greeting message
        id: greet
        run: |
         USERNAME=${{ needs.job1.outputs.username }}
         COLOR=${{ needs.job1.outputs.favorite_color }}
         item=${{ needs.job1.outputs.item }}
         GREETING="Welcome, $USERNAME! you have chosen $COLOR colored $item in our system."
         echo "GREETING=$GREETING" >> $GITHUB_OUTPUT
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo the greeting message
        run: echo "${{ needs.job2.outputs.GREETING }}"
  

