name: Dispatch Workflow
 
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'Doniyor'
      favorite_color:
        description: 'Favorite color'
        required: true
        default: 'white'
 
jobs:
  run_the_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Username and Favorite Color
        run: echo "${{ github.event.inputs.username }} is username, and favorite color is ${{ github.event.inputs.favorite_color }}"
