name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'Doniyor'
      favorite_color:
        description: 'Favorite color'
        required: true
        default: 'white'
      model:
        description: 'Enter your car model'
        required: true
        default: 'Porsche'


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.output-username.outputs.username }}
      favorite_color: ${{ steps.output-favorite-color.outputs.favorite_color }}
      car_model: ${{ steps.output-car-model.outputs.car_model }}
    steps:
      - name: Echo Username
        id: output-username
        run: echo "username=${{ github.event.inputs.username }}" >> $GITHUB_OUTPUT
      - name: Echo Favorite Color
        id: output-favorite-color
        run: echo "favorite_color=${{ github.event.inputs.favorite_color }}" >> $GITHUB_OUTPUT 
      - name: Echo Car Model
        id: output-car-model
        run: echo "car_model=${{ github.event.inputs.model }}" >> $GITHUB_OUTPUT


  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      GREETING: ${{ steps.greet.outputs.GREETING }}
    steps:
      - name: Create a greeting message
        id: greet
        run: |
         USERNAME=${{ needs.job1.outputs.username }}
         COLOR=${{ needs.job1.outputs.favorite_color }}
         CAR_MODEL=${{ needs.job1.outputs.car_model }}
         GREETING="Welcome, $USERNAME! you have chosen $COLOR colored $CAR_MODEL in our system."
         echo "GREETING=$GREETING" >> $GITHUB_OUTPUT
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo the greeting message
        run: echo "${{ needs.job2.outputs.GREETING }}"
