name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'Doniyor'
      favorite_color:
        description: 'Favorite color'
        required: true
        default: 'white'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.output-username.outputs.username }}
      favorite_color: ${{ steps.output-favorite-color.outputs.favorite_color }}
    steps:
      - name: Echo Username
        id: output-username
        run: echo "::set-output name=username::${{ github.event.inputs.username }}"
      - name: Echo Favorite Color
        id: output-favorite-color
        run: echo "::set-output name=favorite_color::${{ github.event.inputs.favorite_color }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      GREETING: ${{ steps.greet.outputs.greeting }}
    steps:
      - name: Create a greeting message
        id: greet
        run: echo "::set-output name=greeting::Bonjour, ${{ needs.job1.outputs.username }}! Your favorite color is ${{ needs.job1.outputs.favorite_color }}."

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo the greeting message
        run: echo "${{ needs.job2.outputs.GREETING }}"
